ALTER TABLE orders ADD COLUMN IF NOT EXISTS cutlery_count INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS apartment TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS entrance TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS floor TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS intercom TEXT DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier_comment TEXT DEFAULT '';
